### PR TITLE
Support for overriding icons per row

### PR DESCRIPTION
**Pull request by torsten-sauer**

### CODE REVIEW

**Comment by TrueDub** [comment]
@torsten-sauer this looks good. As this adds functionality that a user could use, please update the readme file giving an explanation of what it does, and how to use it.

**Comment by torsten-sauer** [comment]
@TrueDub I've added some documentation

**Comment by TrueDub** [comment]
Nice, thanks - will merge now.

**Comment by torsten-sauer** [comment]
Great, thanks!

**Pull request merged**
